server:
  port: 8081
debug: false
spring:
  datasource:
    url: jdbc:mysql://172.18.117.77:3306/collect?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: zjxdqh.123
    initialize: true
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxActive: 20
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mybatis:
    mapper:
      package: com.tcp.mapper
  aop:
    proxy-target-class: false
  rabbitmq:
    host: 172.18.117.77
    port: 5672
    username: zjxdqh
    password: zjxdqh.123
    publisher-confirms: true
    virtual-host: /
    exchange_name: collect_ops_exchange
    queue_name: collect_ops_receive_queue
    queue_next_name: collect_ops_receive_queue_next
    queue_charging_name: collect_ops_receive_queue_charging
    queue_send_name: collect_ops_send_queue
    receive_route_key: collect_ops_receive_route
    send_route_key: collect_ops_send_route


    delay_exchange_name: send_delay_exchange
    send_pile_retry_queue_name: send_pile_retry_queue

            # 桩长时间离线提醒
    off_line_delay_exchange_name: off_line_send_delay_exchange
    off_line_send_pile_retry_queue_name: off_line_send_pile_retry_queue

    listener:
      simple:
        retry:
          # 消息重试
          enabled: true
          # 重试次数
          max-attempts: 2
          # 重试时间间隔
          max-interval: 5000
      concurrency: 5
      max-concurrency: 10
      prefetch: 1
redis:
  standalone:
      ip: 172.18.117.77
#     password: zjxdqh@888
      port: 6379
      pool:
        testOnBorrow: false
        usePool: true
        max-idle: 32
        min-idle: 0
        max-active: 320
        max-wait: 10000
        #默认超时时间1d
        timeOut: 86400
tcp:
  port: 8124
  nodelay: true
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 4
  so:
    keepalive: true
    backlog: 1024